name: Main Test
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v3

      - name: Install Dependencies
        run: |
          git fetch --prune --unshallow --tags
          sudo $pythonLocation/bin/python3 -m pip install -r requirements.txt
          sudo $pythonLocation/bin/python3 -m pip install setuptools --upgrade
          sudo $pythonLocation/bin/python3 -m pip install pytest
          sudo $pythonLocation/bin/python3 -m pip install -e .

      - name: Run Unit Tests
        run: |
          sudo $pythonLocation/bin/python3 -m pytest --import-mode=append tests/

  test-build-pypi:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v3

      - name: Install Twine
        run: sudo pip install twine wheel

      - name: Create the distribution
        run: |
          git fetch --prune --unshallow --tags
          sudo python setup.py sdist bdist_wheel
  test-build-conda:
    needs: run-tests
    runs-on: ubuntu-latest
# sets default shell to remove need for source to run the conda shell
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v3

      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: ""
          miniconda-version: "latest"

      - name: Install the Conda Dependencies
        run: |
          conda config --set always_yes yes --set auto_update_conda false
          conda update conda
          conda install conda-build

# There needs to be an initial git tag to use, otherwise will fail
# git tags MUST be fetched otherwise output will be blank
# bash variables cannot be used in github actions, must use actions specific syntax and methods
      - name: Build the Anaconda Package
        id: condabuild
        run: |
          conda install anaconda-client
          conda config --set anaconda_upload no
          git fetch --prune --unshallow --tags
          VERSION_FROM_GIT_TAG=$(git tag --list "v*[0-9]" --sort=version:refname | tail -1 | cut -c 2-) conda build . -c stanfordcvxgrp -c conda-forge --numpy 1.22.2
          